# http://travis-ci.org/spectralDNS/mpiFFT4py

language: python

sudo: false

matrix:
    include:
        - os: osx
          language: generic
          osx_image: xcode7.2
          env: TOXENV=py27
        - os: osx
          osx_image: xcode7.2
          language: generic
          env: TOXENV=py32

before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
      source /Users/travis/miniconda3/bin/activate root
      conda config --set show_channel_urls true --set binstar_upload true
      conda install conda-build
      
script:
  - conda build -c mpi4py -c conda-forge -c spectralDNS conf/conda
