package:
  name: mpifft4py
  version: "1.0"

source:
  git_url: ../../

build:
  number: 22

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - scipy
    - mpi4py
    - cython
    - pyfftw

test:
  source_files:
    - tests

  requires:
    - pytest
