package:
  name: mpifft4py
  version: "1.1"
  
source:
  git_url: ../../

build:
  number: 16

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - scipy
    - mpi4py
    - cython

test:
    requires:
      - pytest

