package:
  name: mpifft4py
  version: "1.0"
  
source:
  git_url: ../../

build:
  number: 5

requirements:
  build:
    - python
    - cython

  run:
    - python
    - numpy
    - scipy
    - mpi4py

test:
    requires:
      - pytest

